version: '3'
services:
  nginx:
    image: docker.pkg.github.com/toti1212/mwd-docker-compose/nginx-backend:testing-latest
    ports:
      - 80:80
    depends_on:
      - web
  web:
    image: docker.pkg.github.com/toti1212/mwd-docker-compose/flask-backend:testing-latest
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    env_file: ./testing.env
    ports:
    - 5000
    links:
    - redis
  redis:
    image: redis